# This workflow will do a clean install of node dependencies, lint the source code and run tests

name: Continuous Integration

on: pull_request

jobs:
  test-and-lint:
    name: Run tests and lint
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@ee0669bd1cc54295c223e0bb666b733df41de1c5 # v2.7.0
      - name: Install node
        uses: actions/setup-node@f1f314fca9dfce2769ece7d933488f076716723e # v1.4.6
        with:
          node-version: '12.x'
      - run: yarn install
      - run: yarn lint
      - run: yarn typecheck
      - run: yarn test
      - run: yarn audit --groups dependencies
      - run: yarn build
