# This workflow will do a clean install of node dependencies, lint the source code and run tests

name: Continuous Integration

on: pull_request

jobs:
  test-and-lint:
    name: Run tests and lint
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        node: [12, 14, 16]

    steps:
      - uses: actions/checkout@v2
      - name: Install node
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node }}
      - run: yarn install
      - run: yarn lint
      - run: yarn typecheck
      - run: yarn test
      - run: yarn audit --groups dependencies
      - run: yarn build
